# data/database/models.py
"""
SQLAlchemy ORM models.
Every table in the platform is defined here.
"""

from datetime import date, datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, relationship
from sqlalchemy.sql import func


# ─── Base ─────────────────────────────────────────────────────────────────────
class Base(DeclarativeBase):
    pass


# ─── 1. Raw Prices ────────────────────────────────────────────────────────────
class RawPrice(Base):
    """
    Daily OHLCV data fetched from yfinance.
    Incremental loads check this table to avoid re-fetching.
    """
    __tablename__ = "raw_prices"
    __table_args__ = (
        UniqueConstraint("ticker", "date", name="uq_raw_prices_ticker_date"),
    )

    id         = Column(Integer, primary_key=True, autoincrement=True)
    ticker     = Column(String(20), nullable=False, index=True)
    date       = Column(Date, nullable=False, index=True)
    open       = Column(Float, nullable=False)
    high       = Column(Float, nullable=False)
    low        = Column(Float, nullable=False)
    close      = Column(Float, nullable=False)
    adj_close  = Column(Float, nullable=True)
    volume     = Column(BigInteger, nullable=False)
    created_at = Column(DateTime, server_default=func.now())

    def __repr__(self):
        return f"<RawPrice {self.ticker} {self.date} close={self.close}>"


# ─── 2. Feature Store ─────────────────────────────────────────────────────────
class Feature(Base):
    """
    Computed technical indicators and market regime labels.
    Written by feature_engineer.py after raw data is loaded.
    """
    __tablename__ = "features"
    __table_args__ = (
        UniqueConstraint("ticker", "date", name="uq_features_ticker_date"),
    )

    id            = Column(Integer, primary_key=True, autoincrement=True)
    ticker        = Column(String(20), nullable=False, index=True)
    date          = Column(Date, nullable=False, index=True)

    # Moving Averages
    ma_50         = Column(Float, nullable=True)
    ma_200        = Column(Float, nullable=True)

    # Momentum
    rsi_14        = Column(Float, nullable=True)   # 0–100
    macd          = Column(Float, nullable=True)
    macd_signal   = Column(Float, nullable=True)
    macd_hist     = Column(Float, nullable=True)

    # Volatility
    volatility_20 = Column(Float, nullable=True)   # 20-day rolling std of returns
    atr_14        = Column(Float, nullable=True)   # Average True Range

    # Volume
    volume_zscore = Column(Float, nullable=True)   # Z-score vs 20-day avg

    # Market Regime: 'bull', 'bear', 'sideways'
    market_regime = Column(String(20), nullable=True)

    # Price relative to index (SPY)
    rel_strength  = Column(Float, nullable=True)

    created_at    = Column(DateTime, server_default=func.now())

    def __repr__(self):
        return f"<Feature {self.ticker} {self.date} regime={self.market_regime}>"


# ─── 3. Strategy Signals ──────────────────────────────────────────────────────
class StrategySignal(Base):
    """
    BUY / SELL / HOLD signals generated by each strategy for each ticker/date.
    """
    __tablename__ = "strategy_signals"
    __table_args__ = (
        UniqueConstraint(
            "ticker", "date", "strategy_name",
            name="uq_signals_ticker_date_strategy"
        ),
    )

    id            = Column(Integer, primary_key=True, autoincrement=True)
    ticker        = Column(String(20), nullable=False, index=True)
    date          = Column(Date, nullable=False, index=True)
    strategy_name = Column(String(50), nullable=False, index=True)
    signal        = Column(String(10), nullable=False)   # BUY, SELL, HOLD
    created_at    = Column(DateTime, server_default=func.now())

    def __repr__(self):
        return f"<Signal {self.strategy_name} {self.ticker} {self.date}: {self.signal}>"


# ─── 4. Backtest Results ──────────────────────────────────────────────────────
class BacktestResult(Base):
    """
    Daily portfolio value and returns for each strategy backtest run.
    One row per trading day per strategy per experiment.
    """
    __tablename__ = "backtest_results"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    experiment_id   = Column(Integer, ForeignKey("experiments.id"), nullable=False, index=True)
    strategy_name   = Column(String(50), nullable=False)
    ticker          = Column(String(20), nullable=False)
    date            = Column(Date, nullable=False)
    daily_return    = Column(Float, nullable=True)
    portfolio_value = Column(Float, nullable=True)
    signal          = Column(String(10), nullable=True)
    created_at      = Column(DateTime, server_default=func.now())

    experiment      = relationship("Experiment", back_populates="backtest_results")

    def __repr__(self):
        return f"<BacktestResult exp={self.experiment_id} {self.strategy_name} {self.date}>"


# ─── 5. Experiments ───────────────────────────────────────────────────────────
class Experiment(Base):
    """
    An A/B test comparing two strategies on a ticker over a time window.
    """
    __tablename__ = "experiments"

    id             = Column(Integer, primary_key=True, autoincrement=True)
    name           = Column(String(100), nullable=False)
    strategy_a     = Column(String(50), nullable=False)
    strategy_b     = Column(String(50), nullable=False)
    ticker         = Column(String(20), nullable=False)
    start_date     = Column(Date, nullable=False)
    end_date       = Column(Date, nullable=False)
    status         = Column(String(20), default="pending")   # pending, running, completed, failed
    created_at     = Column(DateTime, server_default=func.now())
    completed_at   = Column(DateTime, nullable=True)

    backtest_results  = relationship("BacktestResult", back_populates="experiment")
    experiment_result = relationship("ExperimentResult", back_populates="experiment", uselist=False)

    def __repr__(self):
        return f"<Experiment {self.name} {self.strategy_a} vs {self.strategy_b}>"


# ─── 6. Experiment Results ────────────────────────────────────────────────────
class ExperimentResult(Base):
    """
    Aggregated statistical results of a completed A/B experiment.
    This is the final output: winner, p-value, lift, metrics for both strategies.
    """
    __tablename__ = "experiment_results"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    experiment_id    = Column(Integer, ForeignKey("experiments.id"), nullable=False, unique=True)

    winner           = Column(String(50), nullable=True)
    lift_pct         = Column(Float, nullable=True)       # % improvement of winner
    p_value          = Column(Float, nullable=True)
    is_significant   = Column(Boolean, nullable=True)     # p_value < 0.05
    confidence_level = Column(Float, default=0.95)

    # Strategy A metrics
    sharpe_a         = Column(Float, nullable=True)
    annual_return_a  = Column(Float, nullable=True)
    volatility_a     = Column(Float, nullable=True)
    max_drawdown_a   = Column(Float, nullable=True)
    win_rate_a       = Column(Float, nullable=True)

    # Strategy B metrics
    sharpe_b         = Column(Float, nullable=True)
    annual_return_b  = Column(Float, nullable=True)
    volatility_b     = Column(Float, nullable=True)
    max_drawdown_b   = Column(Float, nullable=True)
    win_rate_b       = Column(Float, nullable=True)

    # Bootstrap CI for Sharpe difference
    ci_lower         = Column(Float, nullable=True)
    ci_upper         = Column(Float, nullable=True)

    test_method      = Column(String(50), default="t-test + mann-whitney + bootstrap")
    created_at       = Column(DateTime, server_default=func.now())

    experiment       = relationship("Experiment", back_populates="experiment_result")

    def __repr__(self):
        return f"<ExperimentResult exp={self.experiment_id} winner={self.winner} p={self.p_value}>"


# ─── 7. ML Predictions ────────────────────────────────────────────────────────
class MLPrediction(Base):
    """
    Stores predictions made by the ML model (best strategy for current conditions).
    """
    __tablename__ = "ml_predictions"

    id                  = Column(Integer, primary_key=True, autoincrement=True)
    ticker              = Column(String(20), nullable=False, index=True)
    date                = Column(Date, nullable=False, index=True)
    predicted_strategy  = Column(String(50), nullable=False)
    confidence          = Column(Float, nullable=True)        # Model probability
    model_name          = Column(String(50), nullable=True)   # xgboost or lightgbm
    mlflow_run_id       = Column(String(100), nullable=True)

    # Snapshot of features used for this prediction (for auditability)
    rsi                 = Column(Float, nullable=True)
    macd                = Column(Float, nullable=True)
    volatility          = Column(Float, nullable=True)
    market_regime       = Column(String(20), nullable=True)
    volume_zscore       = Column(Float, nullable=True)

    created_at          = Column(DateTime, server_default=func.now())

    def __repr__(self):
        return f"<MLPrediction {self.ticker} {self.date}: {self.predicted_strategy} ({self.confidence:.2f})>"
